### SIZES

# Screen
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 924

# Player
PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64

# Objects
PLATFORM_WIDTH = SCREEN_WIDTH / 5
PLATFORM_HEIGHT = SCREEN_HEIGHT // 3
PLATFORM_FLOOR_WIDTH = (
    PLATFORM_WIDTH - 30
)  # Platform width without counting the empty width
BLOCK_WIDTH = 64
BLOCK_HEIGHT = 64
SPIKE_WIDTH = 64
SPIKE_HEIGHT = 64


### GAME OPTIONS

# Speeds
FPS = 120
GAME_SPEED = 5
MAX_GAME_SPEED = 9
GAME_SPEED_INCREMENT_FACTOR = 0.0002
PLAYER_JUMP_SPEED_FACTOR = 2.5

# Options
PLAYER_Y_POS = SCREEN_HEIGHT - (SCREEN_HEIGHT / 5)

# Sprite drop chances
SINGLE_BLOCK_DROP_CHANCE = 1.5
DOUBLE_BLOCK_DROP_CHANCE = 1.25
SPIKE_DROP_CHANCE = 1.6
