### SIZES

# Screen
SCREEN_WIDTH = 680
SCREEN_HEIGHT = 924

# Player
PLAYER_WIDTH = 80
PLAYER_HEIGHT = 80

# Objects
PLATFORM_WIDTH = SCREEN_WIDTH / 5
PLATFORM_HEIGHT = SCREEN_HEIGHT // 3
PLATFORM_FLOOR_WIDTH = (
    PLATFORM_WIDTH - 3
)  # Platform width without counting the empty width
BLOCK_WIDTH = 85
BLOCK_HEIGHT = 85
SPIKE_WIDTH = 85
SPIKE_HEIGHT = 85
DEAD_BUSH_WIDTH = 180
DEAD_BUSH_HEIGHT = 85


### GAME OPTIONS

# Speeds
FPS = 120
GAME_SPEED = 5
MAX_GAME_SPEED = 12
GAME_SPEED_INCREMENT_FACTOR = 0.002
PLAYER_JUMP_SPEED_FACTOR = 1.5
PLAYER_ATTACK_SPEED = 0.2
PLAYER_HIT_ANIMATION_SPEED = 0.1
PLAYER_SHIELD_ANIMATION_SPEED = 0.1
PLAYER_RUN_ANIMATION_SPEED = 0.03

# Options
PLAYER_Y_POS = SCREEN_HEIGHT - (SCREEN_HEIGHT / 5)
MAX_SPRITES_ON_SCREEN = 6
MIN_SPRITES_DISTANCE_FACTOR = 2
MAX_SPRITES_DISTANCE_FACTOR = 12
SPRITES_ON_SCREEN_INCREMENT_FACTOR = 0.005
SPRITES_DISTANCE_DECREMENT_FACTOR = 0.002

# Sprite drop chances
SINGLE_BLOCK_DROP_CHANCE = 2
DOUBLE_BLOCK_DROP_CHANCE = 1.8
SPIKE_DROP_CHANCE = 1.6
DEAD_BUSH_DROP_CHANCE = 1.7
